version: '3.2'

services:
    pgadmin:
      image: chorss/docker-pgadmin4
      restart: always
      ports:
         - 5050:5050
      volumes:
         - ./data/:/home/user/data

networks:
        default: 
            external: 
              name: overlay
