global:
  scrape_interval:     15s

  external_labels:
    monitor: 'fn-monitor'

scrape_configs:
  - job_name: 'functions'
    scrape_interval: 5s
    static_configs:
            - targets: ['strange:8080','fn:8080']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
            - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
            - targets: ['node-exporter:9100']

 
