version: '3.2'

services:
   
    portainer:
      image: portainer/portainer:1.15.1
      ports:
         - 9000:9000
      volumes:
         - ./portainer-data:/data
         - /var/run/docker.sock:/var/run/docker.sock

networks:
        default: 
            external: 
              name: overlay
